/* SPDX-License-Identifier: GPL-2.0-only */
#include "publisher.h"
#include <assert.h>
#include <math.h>
#include <stdio.h>
#include <string.h>

static uint64_t read64(const unsigned char *p)
{
  unsigned i; uint64_t n = 0;
  for (i = 0; i < 8; i++) n |= (uint64_t)p[i] << (8 * i);
  return n;
}
int main(int argc, char **argv)
{
  LU_Publisher p;
  unsigned char policy[32] = {1}, boot[16] = {2}, frame[LU_FRAME_SIZE];
  unsigned char envelope[LU_ENVELOPE_SIZE];
  size_t length;
  struct timespec midpoint = {1700000000, 0}, cooked = {1700000000, 100000000};
  unsigned i;
  assert(LU_Init(&p, policy, boot, 3));
  assert(!LU_Envelope(&p, 1002, 900, 1, 0, 1001, envelope, &length) && !length);
  assert(!LU_Envelope(&p, 1002, 900, 1, UINT32_MAX, 1001, envelope, &length) && !length);
  assert(!LU_Envelope(&p, UINT64_MAX - 998, 900, 1, 246, 1001, envelope, &length) && !length);
  assert(p.round == 0);
  assert(LU_Envelope(&p, 1002, 900, 1, 246, 1001, envelope, &length));
  assert(length > 4 && length < LU_ENVELOPE_SIZE);
  assert((((size_t)envelope[0] << 24) | ((size_t)envelope[1] << 16) |
          ((size_t)envelope[2] << 8) | envelope[3]) == length - 4);
  assert(strstr((char *)envelope + 4, "\"caller\":{\"pid\":246,\"uid\":1001}"));
  assert(strstr((char *)envelope + 4, "\"deadline\":2001,\"deadline_clock\":\"boottime\""));
  assert(LU_Init(&p, policy, boot, UINT64_MAX));
  p.clock = UINT64_MAX; p.round = UINT64_MAX - 1;
  for (i = 0; i < 3; i++) {
    p.sources[i].available = 1; p.sources[i].sequence = UINT64_MAX;
    p.sources[i].observed_ms = UINT64_MAX - 999;
    p.sources[i].lower_ms = p.sources[i].upper_ms = 4102444800000LL;
  }
  assert(LU_Envelope(&p, UINT64_MAX - 999, UINT64_MAX - 999, INT64_MAX, INT32_MAX,
                     UINT32_MAX, envelope, &length));
  assert(length < LU_ENVELOPE_SIZE && envelope[length - 1] == '}');
  assert(LU_Init(&p, policy, boot, 3));
  for (i = 1; i <= 3; i++)
    assert(LU_Observe(&p, i, 1, &midpoint, -0.05, 0.02, 0.003, &cooked, 0.001, 1000, 1001));
  assert(LU_Frame(&p, 1002, 900, 1699999000000LL, frame));
  assert(!memcmp(frame, "LUMAUTC1", 8));
  assert(read64(frame + 136) <= 1700000000036ULL);
  assert(read64(frame + 144) >= 1700000000064ULL);
  assert(read64(frame + 128) == 1001);
  assert(read64(frame + 120) == 1);
  assert(frame[113] == 1 && frame[153] == 1 && frame[193] == 1);
  assert(LU_Frame(&p, 2000, 1900, 1700000000000LL, frame));
  assert(read64(frame + 128) == 1001 && read64(frame + 120) == 1);
  assert(!LU_Observe(&p, 1, 1, &midpoint, NAN, 0, 0, &cooked, 0, 2000, 2001));
  assert(LU_Frame(&p, 2002, 1900, 1700000000000LL, frame) && !frame[113]);
  assert(!LU_Observe(&p, 2, 0, &midpoint, 0, 0, 0, &cooked, 0, 2000, 2001));
  assert(LU_Frame(&p, 2002, 1900, 1700000000000LL, frame) && !frame[153]);
  assert(!LU_Observe(&p, 3, 1, &midpoint, 0, -0.1, 0, &cooked, 0, 2000, 2001));
  assert(!LU_Observe(&p, 3, 1, &midpoint, 0, 0, INFINITY, &cooked, 0, 2000, 2001));
  assert(!LU_Observe(&p, 3, 1, &midpoint, 0, 0, 0, &cooked, 0, 2002, 2001));
  assert(!LU_Observe(&p, 3, 1, &midpoint, 0, 0, 0, &cooked, 0, 2000, 2021));
  cooked.tv_sec += 6;
  assert(!LU_Observe(&p, 3, 1, &midpoint, 0, 0, 0, &cooked, 0, 2000, 2001));
  cooked.tv_sec -= 6;
  assert(LU_Observe(&p, 3, 1, &midpoint, 0, 0, 0, &cooked, 0, 2000, 2001));
  assert(LU_Frame(&p, 181983, 181900, 1700000000000LL, frame) && frame[193] == 1);
  assert(LU_Frame(&p, 181984, 181900, 1700000000000LL, frame) && frame[193] == 0);
  assert(LU_Observe(&p, 3, 1, &midpoint, 0, 0, 0, &cooked, 0, 182000, 182001));
  assert(!LU_Observe(&p, 3, 1, &midpoint, 0, 0, 0, &cooked, 0, 182000, 182001));
  LU_Fence(&p);
  assert(LU_Frame(&p, 182002, 181900, 1700000000000LL, frame));
  assert(read64(frame + 64) == 2 && !frame[193]);
  p.clock = UINT64_MAX; LU_Fence(&p);
  assert(!LU_Frame(&p, 182002, 181900, 1700000000000LL, frame));
  assert(LU_Init(&p, policy, boot, 3));
  p.round = UINT64_MAX;
  assert(!LU_Frame(&p, 1002, 900, 1, frame));
  assert(!LU_Init(&p, policy, boot, 0));
  assert(LU_Init(&p, policy, boot, 3));
  /* Emit the C-produced fixture using the generated byte-exact approved policy. */
  if (argc == 2 || argc == 3) {
    FILE *f;
    #include "luma_policy_digest.h"
    assert(LU_Init(&p, luma_policy_digest, boot, 3));
    assert(LU_Observe(&p, 1, 1, &midpoint, -0.05, 0.02, 0.003, &cooked, 0.001, 1000, 1001));
    assert(LU_Frame(&p, 1002, 900, 1699999000000LL, frame));
    f = fopen(argv[1], "wb"); assert(f);
    assert(fwrite(frame, 1, sizeof(frame), f) == sizeof(frame)); assert(!fclose(f));
    if (argc == 3) {
      assert(LU_Init(&p, luma_policy_digest, boot, 3));
      assert(LU_Observe(&p, 1, 1, &midpoint, -0.05, 0.02, 0.003, &cooked, 0.001, 1000, 1001));
      assert(LU_Envelope(&p, 1002, 900, 1699999000000LL, 246, 1001, envelope, &length));
      f = fopen(argv[2], "wb"); assert(f);
      assert(fwrite(envelope, 1, length, f) == length); assert(!fclose(f));
    }
  }
  puts("UTC_PUBLISHER_C_PASSED");
  return 0;
}
