#!/bin/sh
# Build only the dependency graph for the signed kernel's selected boot mode.
# Unit conditions alone do not prevent systemd from starting device dependencies.
set -eu
cmdline=$(cat /proc/cmdline)
case " $cmdline " in
    *" luma.mode=installed "*)
        mkdir -p "$1/local-fs.target.wants" "$1/multi-user.target.wants"
        ln -s /etc/systemd/system/efi.mount "$1/local-fs.target.wants/efi.mount"
        ln -s /etc/systemd/system/luma-boot-health.service "$1/multi-user.target.wants/luma-boot-health.service"
        if [ -f /var/lib/luma-os/model-selection.json ]; then
            mkdir -p "$1/luma-model.service.d"
            /usr/libexec/luma-os/luma-platform model-unit > "$1/luma-model.service.d/resources.conf"
        fi
        ;;
    *" luma.mode=live "*)
        mkdir -p "$1/multi-user.target.wants" "$1/local-fs.target.wants"
        ln -s /etc/systemd/system/media-luma.mount "$1/local-fs.target.wants/media-luma.mount"
        device_timeout="$1/dev-disk-by\\x2dpartlabel-luma\\x2dpayload.device.d"
        mkdir -p "$device_timeout"
        printf '[Unit]\nJobRunningTimeoutSec=90s\n' > "$device_timeout/timeout.conf"
        consoles=$(cat /sys/class/tty/console/active)
        case " $consoles " in
            *" ttyS0 "*) ln -s /etc/systemd/system/luma-live-console.service "$1/multi-user.target.wants/luma-live-console.service" ;;
        esac
        case " $consoles " in
            *" tty0 "*|*" tty1 "*) ln -s /etc/systemd/system/luma-live-vt.service "$1/multi-user.target.wants/luma-live-vt.service" ;;
        esac
        ;;
esac
